baseURL = "www.yaorongli.com/"
languageCode = "en-us"
title = "Yaorong"


[params]
 copyright = "&copy;2019 coded and designed by yaorong"
 picture = "/img/cat.gif"
 email= "55yaorong.li@gmail.com"
 logo= "/img/logo.png"
 googleAnalytics = "UA-110677231-2"


[params.experience]
[[params.experience.works]]
name= "Product designer"
company= "Adyen"
time= "2018.05 - Now"

[[params.experience.works]]
name= "UX designer"
company= "HERE"
time= "2017.03 - 2018.04"

[[params.experience.works]]
name= "Interaction designer work student"
company= "HERE"
time= "2016. - 2018.04"

[[params.experience.studies]]
name= "Msc. Human computer interaction design"
school= "TU Berlin"
time= "2015.10 - 2017.03"

[[params.experience.studies]]
name= "Msc. Human computer interaction design"
school= "Paris Sud"
time= "2014.09 - 2015.06"

[[params.experience.studies]]
name= "Bsc. Electronic engineering"
school= "BUPT"
time= "2010.09 - 2014.06"

[params.navigation]
[[params.navigation.links]]
name = "Works"
url = "../../"

[[params.navigation.links]]
name = "Me"
url = "../../aboutme/aboutme"

[[params.navigation.links]]
name = "Email"
url = "mailto:55yaorong.li@gmail.com"

[params.contact]
[[params.contact.links]]
name="email"
url="mailto:55yaorong.li@gmail.com"

[[params.contact.links]]
name="linkedin"
url="https://www.linkedin.com/in/%E5%9E%9A%E8%93%89-%E6%9D%8E-b74989b0/"

[[params.contact.links]]
name="facebook"
url="https://www.facebook.com/profile.php?id=100007113309206"

[[params.contact.links]]
name="CV"
url="https://github.com/55aze/hugo/blob/master/src/cv.pdf"

[params.work]
[[params.work.projects]]
name = "KYC Hosted onboarding"
url = "works/adyen"
description = "Hassle-free KYC process to easily onboard users "
role = "Design, Research, Plan"
time = "2019.03 to 2019.07"
company = "Adyen"
cover = "adyen-cover"

[[params.work.projects]]
name = "Izumi Editview"
url = "works/izumi"
description = "One workspace for different users"
role = "UX/UI Design, User Research"
time = "2017.08 to 2017.11"
company = "HERE"
cover = "izumi1"



[[params.work.projects]]
name = "Kao"
url = "works/kao"
role = "UI Design, Documentation design system"
description = "Create a consistent and convenient design system"
company = "HERE"
time = "2016.08 till 2018.03"
cover = "styleguide-cover"




[[params.work.projects]]
name = "Izumi Dashboard"
url = "works/dashboard"
description = "A better navigation system for complicated workflow"
time = "2017.12 till 2018.03"
role = "UX/UI design, User Research"
company = "HERE"
cover = "dashboard-cover"











