baseURL = "www.yaorong-li.com/"
languageCode = "en-us"
title = "Yaorong"


[params]
 copyright = "&copy;2017 code and designed by yaorong li 🖖"
 email= "55yaorong.li@gmail.com"
 logo= "img/logo.png"
 googleAnalytics = "UA-110677231-2"




[params.navigation]

[[params.navigation.links]]
name = "About"
url = "#About"

[[params.navigation.links]]
name = "Works"
url = "#Works"

[[params.navigation.links]]
name = "Contact"
url = "#Contact"



[params.contact]
[[params.contact.links]]
name="email"
url="mailto:55yaorong.li@gmail.com"

[[params.contact.links]]
name="linkedin"
url="https://www.linkedin.com/in/%E5%9E%9A%E8%93%89-%E6%9D%8E-b74989b0/"

[[params.contact.links]]
name="facebook"
url="https://www.facebook.com/profile.php?id=100007113309206"

[[params.contact.links]]
name="CV"
url="https://github.com/55aze/hugo/blob/master/src/file/CV.pdf"

[params.work]
[[params.work.projects]]
name = "Izumi"
url = "works/izumi"
description = "Tools help with localisation process within the company"
role = "UX/UI Design"
time = "2016.05 till Now"
company = "HERE"

[[params.work.projects]]
name = "Clio"
url = "works/clio"
description = "Tools help with localisation process within the company"
role = "ux/ui design"
company = "HERE"


[[params.work.projects]]
name = "Clio"
url = "works/clio"
description = "Tools help with localisation process within the company"
company = "HERE"


[[params.work.projects]]
name = "Clio"
url = "works/clio"
description = "Tools help with localisation process within the company"
company = "HERE"


[[params.work.projects]]
name = "Clio"
url = "works/clio"
description = "Tools help with localisation process within the company"
company = "HERE"


[[params.work.projects]]
name = "Clio"
url = "works/clio"
description = "Tools help with localisation process within the company"
company = "HERE"




