baseURL = "http://yaorong-li.com/"
languageCode = "en-us"
title = ""
publishDir = "docs"


[params]
      copyright = "&copy;2017 yaorong li"
      email= "55yaorong.li@gmail.com"
      logo= "img/logo.svg"

      


